// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3cUMYer2vyAYubEpgA33iRgsrTjDlegA',
    appId: '1:692073318832:web:0cb6e2df0128631f226e75',
    messagingSenderId: '692073318832',
    projectId: 'finaltesttarunvai',
    authDomain: 'finaltesttarunvai.firebaseapp.com',
    storageBucket: 'finaltesttarunvai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_9NV_o2DKFUxSxQS6pwINwasyHOlH0DE',
    appId: '1:692073318832:android:4574e1bcb6d82ba2226e75',
    messagingSenderId: '692073318832',
    projectId: 'finaltesttarunvai',
    storageBucket: 'finaltesttarunvai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKliumyInEKpkIHLVCIhQ-uBskfUn7U4',
    appId: '1:692073318832:ios:1780e7b326ba6cbc226e75',
    messagingSenderId: '692073318832',
    projectId: 'finaltesttarunvai',
    storageBucket: 'finaltesttarunvai.appspot.com',
    iosClientId: '692073318832-2i24q32vd9ismjn7vt61ii87fa9o63b3.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.flutter.app',
  );
}
